eclipse/codewind-openapi-eclipse

dev/ant_build/build-cw.xml, dev/ant_build/cw_imports.xml
=> Issue #7:  fix build image name

README.md
Signed-off-by: Sarah Ishida <sishida@us.ibm.com>
=> Grammatical edits

Jenkinsfile
fixes #10 
Signed-off-by: Joseph Kim kjoseph@ca.ibm.com
=> Issue #10: create latest folder to store the latest build

Jenkinsfile
=> Issue #13: add repository in build result 

Jenkinsfile
=> Update latest folder to have build.info

README.md
Link to mattermost
Signed-off-by: Keith Chong kchong@ca.ibm.com
=> Link to mattermost

README.md, dev/org.eclipse.codewind.openapi.core/.gitignore, dev/org.eclipse.codewind.openapi.feature/feature.xml, dev/org.eclipse.codewind.openapi.ui/.gitignore, dev/org.eclipse.codewind.openapi.ui/plugin.properties, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/Messages.java, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/Messages.properties, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/wizard/AbstractGenerateWizardPage.java, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/wizard/GenerateHtmlWizardPage.java
[24] Add .gitignore, update strings, bump up version
=> [24] Add .gitignore, update strings, bump up version

dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/wizard/AbstractGenerateWizardPage.java, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/wizard/GenerateClientWizardPage.java, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/wizard/GenerateHtmlWizardPage.java
Accessibility issue with Project field
PR for https://github.com/eclipse/codewind-openapi-eclipse/issues/26
=> [26] Accessibility issue with Project field

dev/org.eclipse.codewind.openapi.core/META-INF/MANIFEST.MF, dev/org.eclipse.codewind.openapi.core/build.properties, dev/org.eclipse.codewind.openapi.core/plugin.properties, dev/org.eclipse.codewind.openapi.core/plugin.xml, dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/contenttype/IOpenApiContentDetector.java, dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/contenttype/OpenApiContentDescriber.java, dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/contenttype/OpenApiContentDetector.java, dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/contenttype/OpenApiJsonContentDescriber.java, dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/contenttype/OpenApiJsonContentDetector.java, dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/contenttype/OpenApiYamlContentDescriber.java, dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/contenttype/OpenApiYamlContentDetector.java, dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/util/Util.java, dev/org.eclipse.codewind.openapi.ui/plugin.xml, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/util/OpenApiToolsPropertyTester.java
Add content type for Open API Definition files
Fixes #20 
=> [20] Add content type for Open API Definition files

dev/org.eclipse.codewind.openapi.core/plugin.xml
Fixes #50 .   See #50 for more details.
=> [50] Change JSON OpenAPI content type's parent

dev/org.eclipse.codewind.openapi.test/META-INF/MANIFEST.MF, dev/org.eclipse.codewind.openapi.test/src/org/eclipse/codewind/openapi/test/BaseTestCase.java, dev/org.eclipse.codewind.openapi.test/src/org/eclipse/codewind/openapi/test/util/TestUtilities.java
[48] Pull out useful methods to util class for use by new UI tests
Fixes #48 
=> [48] Pull out useful methods to util class for use by new UI tests

dev/org.eclipse.codewind.openapi.ui.test/.classpath, dev/org.eclipse.codewind.openapi.ui.test/.gitignore, dev/org.eclipse.codewind.openapi.ui.test/.project, dev/org.eclipse.codewind.openapi.ui.test/.settings/org.eclipse.jdt.core.prefs, dev/org.eclipse.codewind.openapi.ui.test/META-INF/MANIFEST.MF, dev/org.eclipse.codewind.openapi.ui.test/build.properties, dev/org.eclipse.codewind.openapi.ui.test/src/org/eclipse/codewind/openapi/ui/test/Activator.java, dev/org.eclipse.codewind.openapi.ui.test/src/org/eclipse/codewind/openapi/ui/test/AllUiTests.java, dev/org.eclipse.codewind.openapi.ui.test/src/org/eclipse/codewind/openapi/ui/test/BaseTestCase.java, dev/org.eclipse.codewind.openapi.ui.test/src/org/eclipse/codewind/openapi/ui/test/UIConstants.java, dev/org.eclipse.codewind.openapi.ui.test/src/org/eclipse/codewind/openapi/ui/test/menus/ContextMenuTest.java, dev/org.eclipse.codewind.openapi.ui.test/src/org/eclipse/codewind/openapi/ui/test/menus/utils/UITestUtilities.java
[44] Create new SWTBot, UI-based test plugin
Fixes #44 
=> [44] Create new SWTBot, UI-based test plugin

ISSUE_TEMPLATE/where-to-report-issues.md
Instruct user to open issues against the main Codewind repo.
=> Add issue template

dev/org.eclipse.codewind.openapi.base.feature/feature.xml, dev/org.eclipse.codewind.openapi.core/META-INF/MANIFEST.MF, dev/org.eclipse.codewind.openapi.feature/feature.xml, dev/org.eclipse.codewind.openapi.test/META-INF/MANIFEST.MF, dev/org.eclipse.codewind.openapi.ui/META-INF/MANIFEST.MF
=> [47] Bump up version numbers for 0.5.0

dev/org.eclipse.codewind.openapi.core/META-INF/MANIFEST.MF, dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/Activator.java, dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/maven/Constants.java, dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/maven/MavenTracker.java, dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/maven/Utils.java, dev/org.eclipse.codewind.openapi.ui/META-INF/MANIFEST.MF, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/Activator.java, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/Constants.java, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/Messages.java, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/Messages.properties, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/commands/PostGenCommand.java, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/wizard/AbstractGenerateWizard.java, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/wizard/AbstractGenerateWizardPage.java
=> [60] Post-codegen improvements for Liberty Maven project types

dev/org.eclipse.codewind.openapi.ui/build.properties
=> [65] Icons do not appear in menus and wizards

dev/org.eclipse.codewind.openapi.ui/build.properties
=> [65] Icons do not appear in menus and wizards - for 0.5.0 branch

dev/ant_build/build-cw.xml, dev/org.eclipse.codewind.openapi.feature/category.xml
=> [69] Version changes necessary for other files

dev/ant_build/build-cw.xml, dev/org.eclipse.codewind.openapi.feature/category.xml, dev/org.eclipse.codewind.openapi.ui/build.properties
Fixes #69 for Master
Signed-off-by: Keith Chong kchong@ca.ibm.com
=> [69] Other files require version changes for Master

dev/org.eclipse.codewind.openapi.ui.test/src/org/eclipse/codewind/openapi/ui/test/AllUiTests.java, dev/org.eclipse.codewind.openapi.ui.test/src/org/eclipse/codewind/openapi/ui/test/BaseTestCase.java, dev/org.eclipse.codewind.openapi.ui.test/src/org/eclipse/codewind/openapi/ui/test/wizard/WizardTest.java
Add 3 openapi wizard testsL: gen html, client and server code.
=> Add openapi wizard test

dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/IOpenApiConstants.java, dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/util/Util.java, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/Constants.java, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/wizard/AbstractGenerateWizardPage.java, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/wizard/GenerateServerWizardPage.java
Fixes #63 .  Have a look at the screenshot for MP in #63.   For Codewind Spring Boot projects, only the spring generator is listed (no screenshot for that)
=> [63] For Codewind projects, use a subset of all server generators

dev/ant_build/build-cw.xml, dev/org.eclipse.codewind.openapi.feature/category.xml, dev/org.eclipse.codewind.openapi.feature/feature.xml
Feature version is out of date
=> Update feature to 0.6.0

dev/ant_build/build-cw.xml, dev/org.eclipse.codewind.openapi.base.feature/feature.xml, dev/org.eclipse.codewind.openapi.core/META-INF/MANIFEST.MF, dev/org.eclipse.codewind.openapi.feature/category.xml, dev/org.eclipse.codewind.openapi.feature/feature.xml, dev/org.eclipse.codewind.openapi.ui/META-INF/MANIFEST.MF
Fixes https://github.com/eclipse/codewind/issues/1376
=> [1376] OpenAPI: Eclipse: Bump up version number for 0.7.0

Jenkinsfile
=> Test jenkins 4

Jenkinsfile
=> add scripts

Jenkinsfile
=> modify jenkinsfile

Jenkinsfile
=> remove jdk

Jenkinsfile
=> fix script

Jenkinsfile
=> change files

dev/gradle.properties
change eclipse version and target platform version
=> change eclipse version and target platform version

Jenkinsfile, dev/run.sh, dev/runTest.sh
Fixed the build failure issue on https://github.com/eclipse/codewind-openapi-eclipse/pull/111. 
The actual test codes are added by @travis1111
=> Add test codes and fix the build failure

Jenkinsfile
=> junit test

Jenkinsfile
It fixes the intermittent build failure issue.
=> Fix build failure issue on post steps and move it within test stage

dev/buildAll.gradle, dev/org.eclipse.codewind.openapi.core/.classpath, dev/org.eclipse.codewind.openapi.core/META-INF/MANIFEST.MF, dev/org.eclipse.codewind.openapi.core/src/org/eclipse/codewind/openapi/core/IOpenApiConstants.java, dev/org.eclipse.codewind.openapi.test/src/org/eclipse/codewind/openapi/test/server/nodejs/NodeJsServerTest.java, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/Constants.java, dev/org.eclipse.codewind.openapi.ui/src/org/eclipse/codewind/openapi/ui/commands/AbstractOpenApiGeneratorCommand.java
Fixes #82 
Signed-off-by: Keith Chong kchong@ca.ibm.com
=> Update to 4.2.2 to pick up node-express-server generator

dev/ant_build/build-cw.xml, dev/org.eclipse.codewind.openapi.base.feature/feature.xml, dev/org.eclipse.codewind.openapi.core/META-INF/MANIFEST.MF, dev/org.eclipse.codewind.openapi.feature.test/category.xml, dev/org.eclipse.codewind.openapi.feature.test/feature.xml, dev/org.eclipse.codewind.openapi.feature/category.xml, dev/org.eclipse.codewind.openapi.feature/feature.xml, dev/org.eclipse.codewind.openapi.test/META-INF/MANIFEST.MF, dev/org.eclipse.codewind.openapi.ui/META-INF/MANIFEST.MF
Fixes https://github.com/eclipse/codewind/issues/1649
=> [1649] Bump up eclipse feature and plugin versions for 0.8.0

dev/ant_build/build-cw.xml, dev/org.eclipse.codewind.openapi.feature.test/category.xml, dev/org.eclipse.codewind.openapi.feature.test/feature.xml, dev/org.eclipse.codewind.openapi.feature/category.xml, dev/org.eclipse.codewind.openapi.feature/feature.xml
Fixes for Eclipse for https://github.com/eclipse/codewind/issues/2312
=> [2312] [OpenAPI] Bump up version numbers

dev/ant_build/build-cw.xml, dev/org.eclipse.codewind.openapi.feature.test/category.xml, dev/org.eclipse.codewind.openapi.feature.test/feature.xml, dev/org.eclipse.codewind.openapi.feature/category.xml, dev/org.eclipse.codewind.openapi.feature/feature.xml
Reverts eclipse/codewind-openapi-eclipse#136
=> Revert "[2312] [OpenAPI] Bump up version numbers"

dev/ant_build/build-cw.xml, dev/org.eclipse.codewind.openapi.feature.test/category.xml, dev/org.eclipse.codewind.openapi.feature.test/feature.xml, dev/org.eclipse.codewind.openapi.feature/category.xml, dev/org.eclipse.codewind.openapi.feature/feature.xml
Fixes https://github.com/eclipse/codewind/issues/2501
=> [2501] Bump up version number for 0.11.0

Jenkinsfile
Publish builds to archive site
=> Issue #2700: Publish to archive site

dev/ant_build/build-cw.xml, dev/org.eclipse.codewind.openapi.feature.test/category.xml, dev/org.eclipse.codewind.openapi.feature.test/feature.xml, dev/org.eclipse.codewind.openapi.feature/category.xml, dev/org.eclipse.codewind.openapi.feature/feature.xml
Updating the version to 0.12.0
=> Update versions to 0.12.0

dev/ant_build/build-cw.xml, dev/org.eclipse.codewind.openapi.feature.test/category.xml, dev/org.eclipse.codewind.openapi.feature.test/feature.xml, dev/org.eclipse.codewind.openapi.feature/category.xml, dev/org.eclipse.codewind.openapi.feature/feature.xml
To fix: eclipse/codewind#3013
Based on the changes from last time: https://github.com/eclipse/codewind-openapi-eclipse/commit/e292f7e2d86f1ae4a57de3028a4bee3a169560f7
=> Update to 0.13.0

dev/ant_build/build-cw.xml, dev/buildAll.gradle, dev/org.eclipse.codewind.openapi.feature.test/category.xml, dev/org.eclipse.codewind.openapi.feature.test/feature.xml, dev/org.eclipse.codewind.openapi.feature/category.xml, dev/org.eclipse.codewind.openapi.feature/feature.xml
Fixes https://github.com/eclipse/codewind/issues/3174 for Eclipse
=> [OpenAPI] Bump up version numbers for 0.14.0

dev/ant_build/build-cw.xml, dev/org.eclipse.codewind.openapi.feature.test/category.xml, dev/org.eclipse.codewind.openapi.feature.test/feature.xml, dev/org.eclipse.codewind.openapi.feature/category.xml, dev/org.eclipse.codewind.openapi.feature/feature.xml
Fixes https://github.com/eclipse/codewind/issues/3211
=> [3211] Bump up version for 0.14.1
